spring:
    datasource:
      url: jdbc:mysql://192.168.3.99/srm
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    profiles:
      active: dev
    resources:
      #staticLocations: src/main/static
    
server:
    port: 9001
    
mybatis:
    mapper-locations:
      classpath:mapper/*.xml
    type-aliases-package: org.dy.example.model
    
info:
   app:
    encoding:UTF-8
   java:
      source:1.7
      target:1.7

endpoints:
  health:
     path:/local_health
     
management:
  context-path: /manager
  port: 8081
  
logging:
  config: classpath:config/log4j2-${spring.profiles.active}.json